### ISSUE TITLE
Iniciar proyecto de Vue

### ISSUE THREAD

**Issue by jlram** [jlram/lumenes-web#1]
Inicializar proyecto de Vue con README.md para poder ejecutarlo y visualizarlo todos

**Comment by victorst79** [comment]
Metas:

- [ ] Proyecto genereado.
- [ ] Componente ejemplo.
- [ ] Componente cabecera.
- [ ] Router configuracion.
- [ ] Readme modificado.

Cerrado con el commit [update readme](https://github.com/jlram/lumenes-web/commit/f9036b1323a0057b374ce01899c8a150284e11d4)
